# Generated by Django 2.2.4 on 2019-08-21 03:51

from django.db import migrations, transaction
from django.db.utils import IntegrityError
import os.path
import json

class Migration(migrations.Migration):
    def load_minerals(apps, schema_editor):
        Mineral = apps.get_model("minerals", "Mineral")

        with open(os.path.abspath('minerals/data/minerals.json')) as jsonfile:
            mineral_data = json.load(jsonfile)
            for item in mineral_data:
                with transaction.atomic():
                    try:
                        Mineral.objects.create(**item)
                    except IntegrityError:
                        continue

    def delete_minerals(apps, schema_editor):
        Mineral = apps.get_model("minerals", "Mineral")
        Mineral.objects.all().delete()

    dependencies = [
        ('minerals', '0002_auto_20190821_0241'),
    ]

    operations = [
        migrations.RunPython(load_minerals, delete_minerals),
    ]
